abstract class AppStrings {
  static const String appName = 'UpTodo',
      skip = 'Skip',
      next = 'Next',
      back = 'Back',
      getStarted = 'Get Started',
      onBoardingTitleOne = 'Manage your tasks',
      onBoardingSubTitleOne =
          'You can easily manage all of your daily tasks in DoMe for free',
      onBoardingTitleTwo = 'Create daily routine',
      onBoardingSubTitleTwo =
          'In Uptodo  you can create your personalized routine to stay productive',
      onBoardingTitleThree = 'Organize your tasks',
      onBoardingSubTitleThree =
          'You can organize your daily tasks by adding your tasks into separate categories',
      today = 'Today',
      noTaskTitle = 'What do you want to do today?',
      noTaskSubTitle = 'Tap + to add your tasks',
      addTask = 'Add Task',
      tilte = 'Title',
      tilteHint = 'Enter title here',
      note = 'Note',
      notehint = 'Enter note here',
      date = 'Date',
      startTime = 'Start Time',
      endTime = 'End Time',
      color = 'Color',
      createTask = 'Create task',
      toDo = 'TODO',
      completed = 'COMPLETED',
      taskCompleted = 'Task Completed',
      deleteTask = 'Delete Task',
      cancel = 'Cancel',
      onBoardingKey = 'onBoaring',
      noteErrorMsg = 'Enter Valid Note',
      tilteErrorMsg = 'Enter Valid Title',
      dateErrorMsg = 'Enter Valid Date',
      endTimeErrorMsg = 'Enter Valid End Time',
      createTaskMsg = 'The task was created successfully';
}
